config/routes.rb
SoulmateTest::Application.routes.draw do
  resources :users, :only => [ :index, :show, :edit, :update ] do
    collection do
      get :autocomplete
    end
  end

  resources :words, :only => [ :index, :show ] do
    collection do
      get :autocomplete
    end
  end

  root :to => 'words#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :age, :name

  after_save :do_after_save

  def self.search(term)
    matches = Soulmate::Matcher.new('users').matches_for_term(term, :limit => 20, :cache => Rails.env.production?)
    matches.collect { |match| { "id" => match['id'], 'label' => match['term'], 'value' => match['term'] } }
  end

  private

  def do_after_save
    loader = Soulmate::Loader.new('users')
    loader.add('term' => name, 'score' => age, 'id' => id)
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :word

  after_save :do_after_save

  def self.search(term)
    matches = Soulmate::Matcher.new('word').matches_for_term(term, :limit => 20, :cache => Rails.env.production?)
    matches.collect { |match| { "id" => match["id"], "label" => match["term"], "value" => match["term"] } }
  end

  private

  def do_after_save
    loader = Soulmate::Loader.new('word')
    loader.add('term' => word, 'id' => id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  def index
    @user = User.find_by_name(params[:user][:name]) if params[:user]
  end

  # GET /users/:id
  def show
    @user = User.find(params[:id])
  end

  # GET /users/:id/edit
  def edit
    @user = User.find(params[:id])
  end

  # PUT /users/:id
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # GET /users/autocomplete
  def autocomplete
    render :json => User.search(params['term'])
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  def index
    @word = Word.find_by_word(params[:word][:word]) if params[:word]
  end

  # GET /words/:id
  def show
    @word = Word.find_by_word(params[:word])
  end

  # GET /words/autocomplete?term=term
  def autocomplete
    render :json => Word.search(params['term'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoulmateTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div style="width: 800px; margin: 0 auto;">
<%= yield %>
</div>

</body>
</html>

app/views/users/_form.html.haml
= form_for @user do |f|
  = f.label :name
  = f.text_field :name
  = f.label :age
  = f.text_field :age
  = f.submit

app/views/users/edit.html.haml
%h1 Edit User

= render 'form'

app/views/users/index.html.haml
%h1 Users
%hr

- if @user
  %p You have selected:
  %h2= link_to @user.name, @user
  %p Or, select another user below.

%hr
= form_tag users_path, :method => :get do |f|
  = text_field :user, 'name'
  = submit_tag

app/views/users/show.html.haml
%h1= @user.name
%h3
  Age:
  = @user.age

app/views/words/index.html.haml
%h1 Words
%hr

- if @word
  %p You have selected:
  %h2= @word.word
  %p Or, select another word below.

%hr
= form_tag words_path, :method => :get do |f|
  = text_field :word, 'word'
  = submit_tag

app/views/words/show.html.haml
%h1= @word